In [1]:
import pandas as pd
df=pd.read_excel('india_weather_rainfall_data.xlsx')
print(df)

       date_of_record     month  season            station_name state  \
0          2021-01-02   January  Winter                 Gulmarg    JK
1          2021-01-03   January  Winter                 Gulmarg    JK
2          2021-01-04   January  Winter                 Gulmarg    JK
3          2021-01-05   January  Winter                 Gulmarg    JK
4          2021-01-06   January  Winter                 Gulmarg    JK
...               ...       ...     ...                     ...   ...
970334     2025-02-06  February  Winter  Vizagapatam / Gajuwaka    AP
970335     2025-02-07  February  Winter  Vizagapatam / Gajuwaka    AP
970336     2025-02-08  February  Winter  Vizagapatam / Gajuwaka    AP
970337     2025-02-09  February  Winter  Vizagapatam / Gajuwaka    AP
970338     2025-02-10  February  Winter  Vizagapatam / Gajuwaka    AP

             district  avg_temp  min_temp  max_temp  wind_speed  air_pressure  \
0           Baramulla      -2.2      -6.6      -0.8         2.2        1020.0
1           Baramulla      -3.6      -4.6      -1.8         3.7        1019.5
2           Baramulla      -3.0      -4.5      -1.1         2.1        1022.0
3           Baramulla      -3.3      -5.1      -1.2         2.8        1015.6
4           Baramulla      -3.9      -8.3      -1.0         3.4        1015.3
...               ...       ...       ...       ...         ...           ...
970334  Visakhapatnam      27.3      22.0      34.0         7.6        1011.4
970335  Visakhapatnam      26.7      23.0      30.0         7.7        1013.1
970336  Visakhapatnam      26.5      23.0      30.0         8.7        1013.0
970337  Visakhapatnam      26.5      23.0      30.0         8.5        1012.8
970338  Visakhapatnam      25.5      21.8      31.0         8.2        1013.9

        elevation  latitude  longitude  rainfall
0            2652   34.0500    74.4000       0.1
1            2652   34.0500    74.4000       4.4
2            2652   34.0500    74.4000       2.3
3            2652   34.0500    74.4000      35.0
4            2652   34.0500    74.4000      25.5
...           ...       ...        ...       ...
970334          5   17.7167    83.2333       0.0
970335          5   17.7167    83.2333       0.3
970336          5   17.7167    83.2333       0.0
970337          5   17.7167    83.2333       0.0
970338          5   17.7167    83.2333       0.0

[970339 rows x 15 columns]

In [ ]:
df.head(10)

,date_of_record,month,season,station_name,state,district,avg_temp,min_temp,max_temp,wind_speed,air_pressure,elevation,latitude,longitude,rainfall
0,2021-01-02,January,Winter,Gulmarg,JK,Baramulla,-2.2,-6.6,-0.8,2.2,1020.0,2652,34.05,74.4,0.1
1,2021-01-03,January,Winter,Gulmarg,JK,Baramulla,-3.6,-4.6,-1.8,3.7,1019.5,2652,34.05,74.4,4.4
2,2021-01-04,January,Winter,Gulmarg,JK,Baramulla,-3.0,-4.5,-1.1,2.1,1022.0,2652,34.05,74.4,2.3
3,2021-01-05,January,Winter,Gulmarg,JK,Baramulla,-3.3,-5.1,-1.2,2.8,1015.6,2652,34.05,74.4,35.0
4,2021-01-06,January,Winter,Gulmarg,JK,Baramulla,-3.9,-8.3,-1.0,3.4,1015.3,2652,34.05,74.4,25.5
5,2021-01-07,January,Winter,Gulmarg,JK,Baramulla,-7.5,-10.8,-1.6,5.0,1015.1,2652,34.05,74.4,0.0
6,2021-01-08,January,Winter,Gulmarg,JK,Baramulla,-9.2,-13.0,-3.0,5.7,1012.9,2652,34.05,74.4,0.0
7,2021-01-09,January,Winter,Gulmarg,JK,Baramulla,-9.3,-13.1,-4.0,4.1,1015.3,2652,34.05,74.4,0.0
8,2021-01-10,January,Winter,Gulmarg,JK,Baramulla,-6.8,-12.9,-0.2,3.6,1015.8,2652,34.05,74.4,0.0
9,2021-01-11,January,Winter,Gulmarg,JK,Baramulla,-4.4,-9.6,-0.8,3.4,1017.0,2652,34.05,74.4,0.0

In [3]:
df.tail(10)

,date_of_record,month,season,station_name,state,district,avg_temp,min_temp,max_temp,wind_speed,air_pressure,elevation,latitude,longitude,rainfall
970329,2025-02-01,February,Winter,Vizagapatam / Gajuwaka,AP,Visakhapatnam,25.1,21.0,31.2,7.8,1011.9,5,17.7167,83.2333,0.0
970330,2025-02-02,February,Winter,Vizagapatam / Gajuwaka,AP,Visakhapatnam,26.1,21.0,33.0,7.5,1012.1,5,17.7167,83.2333,0.0
970331,2025-02-03,February,Winter,Vizagapatam / Gajuwaka,AP,Visakhapatnam,26.4,20.0,34.0,7.9,1011.5,5,17.7167,83.2333,0.0
970332,2025-02-04,February,Winter,Vizagapatam / Gajuwaka,AP,Visakhapatnam,25.3,20.0,31.0,8.4,1012.2,5,17.7167,83.2333,0.0
970333,2025-02-05,February,Winter,Vizagapatam / Gajuwaka,AP,Visakhapatnam,26.5,22.0,32.0,7.4,1011.5,5,17.7167,83.2333,0.0
970334,2025-02-06,February,Winter,Vizagapatam / Gajuwaka,AP,Visakhapatnam,27.3,22.0,34.0,7.6,1011.4,5,17.7167,83.2333,0.0
970335,2025-02-07,February,Winter,Vizagapatam / Gajuwaka,AP,Visakhapatnam,26.7,23.0,30.0,7.7,1013.1,5,17.7167,83.2333,0.3
970336,2025-02-08,February,Winter,Vizagapatam / Gajuwaka,AP,Visakhapatnam,26.5,23.0,30.0,8.7,1013.0,5,17.7167,83.2333,0.0
970337,2025-02-09,February,Winter,Vizagapatam / Gajuwaka,AP,Visakhapatnam,26.5,23.0,30.0,8.5,1012.8,5,17.7167,83.2333,0.0
970338,2025-02-10,February,Winter,Vizagapatam / Gajuwaka,AP,Visakhapatnam,25.5,21.8,31.0,8.2,1013.9,5,17.7167,83.2333,0.0

In [4]:
df.describe()

,date_of_record,avg_temp,min_temp,max_temp,wind_speed,air_pressure,elevation,latitude,longitude,rainfall
count,970339,970339.000000,926441.000000,859741.000000,695895.000000,665675.000000,970339.000000,970339.000000,970339.000000,712785.000000
mean,2021-03-27 08:51:14.557654,25.661709,20.647342,31.195383,9.432732,1009.437663,298.181018,20.793670,79.426826,5.267533
min,2015-01-01 00:00:00,-10.400000,-18.500000,-5.600000,0.000000,922.600000,0.000000,7.983300,68.850000,0.000000
25%,2019-03-07 00:00:00,23.100000,17.100000,28.500000,6.100000,1005.800000,16.000000,15.850000,75.400000,0.000000
50%,2021-11-09 00:00:00,26.700000,22.400000,31.600000,8.400000,1009.800000,139.000000,21.616700,78.066700,0.000000
75%,2023-06-24 00:00:00,29.100000,25.000000,34.400000,11.600000,1013.300000,436.000000,25.566700,82.716700,4.000000
max,2025-02-10 00:00:00,43.400000,36.600000,87.000000,66.600000,1036.500000,2652.000000,34.083300,95.383300,485.900000
std,NaN,5.438133,6.008171,5.464499,4.979263,5.292871,415.266215,6.328275,5.852512,14.444142

In [6]:
df.dtypes

date_of_record    datetime64[us]
month                        str
season                       str
station_name                 str
state                        str
district                     str
avg_temp                 float64
min_temp                 float64
max_temp                 float64
wind_speed               float64
air_pressure             float64
elevation                  int64
latitude                 float64
longitude                float64
rainfall                 float64
dtype: object

In [7]:
df.isnull().any()

date_of_record    False
month             False
season            False
station_name      False
state             False
district          False
avg_temp          False
min_temp           True
max_temp           True
wind_speed         True
air_pressure       True
elevation         False
latitude          False
longitude         False
rainfall           True
dtype: bool

In [8]:
df.isnull().sum()

date_of_record         0
month                  0
season                 0
station_name           0
state                  0
district               0
avg_temp               0
min_temp           43898
max_temp          110598
wind_speed        274444
air_pressure      304664
elevation              0
latitude               0
longitude              0
rainfall          257554
dtype: int64

In [10]:
df_fill=df.fillna(0)
df_fill

,date_of_record,month,season,station_name,state,district,avg_temp,min_temp,max_temp,wind_speed,air_pressure,elevation,latitude,longitude,rainfall
0,2021-01-02,January,Winter,Gulmarg,JK,Baramulla,-2.2,-6.6,-0.8,2.2,1020.0,2652,34.0500,74.4000,0.1
1,2021-01-03,January,Winter,Gulmarg,JK,Baramulla,-3.6,-4.6,-1.8,3.7,1019.5,2652,34.0500,74.4000,4.4
2,2021-01-04,January,Winter,Gulmarg,JK,Baramulla,-3.0,-4.5,-1.1,2.1,1022.0,2652,34.0500,74.4000,2.3
3,2021-01-05,January,Winter,Gulmarg,JK,Baramulla,-3.3,-5.1,-1.2,2.8,1015.6,2652,34.0500,74.4000,35.0
4,2021-01-06,January,Winter,Gulmarg,JK,Baramulla,-3.9,-8.3,-1.0,3.4,1015.3,2652,34.0500,74.4000,25.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
970334,2025-02-06,February,Winter,Vizagapatam / Gajuwaka,AP,Visakhapatnam,27.3,22.0,34.0,7.6,1011.4,5,17.7167,83.2333,0.0
970335,2025-02-07,February,Winter,Vizagapatam / Gajuwaka,AP,Visakhapatnam,26.7,23.0,30.0,7.7,1013.1,5,17.7167,83.2333,0.3
970336,2025-02-08,February,Winter,Vizagapatam / Gajuwaka,AP,Visakhapatnam,26.5,23.0,30.0,8.7,1013.0,5,17.7167,83.2333,0.0
970337,2025-02-09,February,Winter,Vizagapatam / Gajuwaka,AP,Visakhapatnam,26.5,23.0,30.0,8.5,1012.8,5,17.7167,83.2333,0.0
970338,2025-02-10,February,Winter,Vizagapatam / Gajuwaka,AP,Visakhapatnam,25.5,21.8,31.0,8.2,1013.9,5,17.7167,83.2333,0.0

In [15]:
groudped_agg=df.groupby('date_of_record')['rainfall'].agg(['mean','sum','count'])
groudped_agg

                    mean    sum  count
date_of_record
2015-01-01      6.512121  214.9     33
2015-01-02      4.852632  276.6     57
2015-01-03      3.307018  188.5     57
2015-01-04      3.352778  120.7     36
2015-01-05      2.793333   41.9     15
...                  ...    ...    ...
2025-02-06      0.049144   20.1    409
2025-02-07      0.044499   18.2    409
2025-02-08      0.018337    7.5    409
2025-02-09      0.081174   33.2    409
2025-02-10      0.381663  156.1    409

[3694 rows x 3 columns]

In [16]:
grouped_mean=df.groupby('season')['rainfall'].mean()
print(grouped_mean)

season
Monsoon         10.547765
Post-monsoon     4.031521
Summer           5.127311
Winter           1.165040
Name: rainfall, dtype: float64

In [20]:
grouped_mean=df.groupby('station_name')['rainfall'].sum().idxmax()
print(grouped_mean)

Mahabaleshwar

In [21]:
grouped_mean=df.groupby('date_of_record')['rainfall'].sum().idxmax()
print(grouped_mean)

2021-07-18 00:00:00

In [28]:
grouped_mean=df.groupby('avg_temp')['rainfall'].mean()
print(grouped_mean)

avg_temp
-10.4    0.00
-9.3     0.00
-9.2     0.05
-9.0     0.00
-8.8     0.00
         ...
 43.0     NaN
 43.1     NaN
 43.2    0.00
 43.3     NaN
 43.4     NaN
Name: rainfall, Length: 514, dtype: float64

In [22]:
grouped_mean=df.groupby('month')['rainfall'].sum().idxmax()
print(grouped_mean)

July

In [33]:
state_rain = df.groupby('state')['rainfall'].mean()
rain_heavy_states = state_rain[state_rain > state_rain.mean()]
print(rain_heavy_states)

state
AN     7.615915
AR    14.406782
AS     8.529321
GA    12.384566
KA     5.956965
KL     9.207976
MH     6.187980
ML     8.759240
PY     6.982184
SK    11.148825
TR     8.759728
WB     6.041968
Name: rainfall, dtype: float64

In [26]:
dry_states=state_rain[state_rain<state_rain.mean()]
print(dry_states)

state
AP    3.944474
BR    4.540533
CH    4.007622
CT    3.619564
DD    5.508145
DL    4.362214
GJ    3.747032
HP    4.302004
HR    2.465838
JK    3.883696
LD    5.752092
MN    4.858749
MP    4.003333
MZ    4.614219
NL    4.487840
OR    5.412132
PB    2.990654
RJ    2.372634
TN    4.928744
UP    4.221811
Name: rainfall, dtype: float64